version: '3'

services:
  app:
    image: 'demo:latest'
    build:
      context: .
    ports:
      - "8080:8080"
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/student
      - SPRING_DATASOURCE_USERNAME=student
      - SPRING_DATASOURCE_PASSWORD=student
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=student
      - POSTGRES_PASSWORD=student